### ISSUE TITLE
setup.py does not include chardet

### ISSUE THREAD

**Issue by zoomequipd** [csirtgadgets/py-cgmail#22]
Steps to reproduce from a centos7 .5 (7.5.1511)
```
$ sudo yum install epel-release; sudo yum install libxslt-devel libxml2-devel python-pip python-devel zlib-devel
$ sudo pip install --upgrade pip
$ sudo pip install --upgrade lxml
$ sudo pip install cssselect
$ git clone https://github.com/csirtgadgets/py-cgmail.git
$ cd py-cgmail
$ sudo pip install . 
$ python test/test_single_html_01.py
Traceback (most recent call last):
  File "test/test_single_html_01.py", line 3, in <module>
    import cgmail
  File "/usr/lib/python2.7/site-packages/cgmail/__init__.py", line 6, in <module>
    import chardet
ImportError: No module named chardetd chardet
```

I'll submit a PR shortly to include chardet in setup.py

**Comment by zoomequipd** [comment]
Based on previous CircleCI builds, it looks like the below might be the preferred method to install the requirements instead of depending on the setup.py file to include them.  Does this just needs added to the install directions instead? 

`if [ -e requirements.txt ]; then pip install -r requirements.txt;else pip install -r requirements.pip;fi`

 Sorry, if that's a normal thing to do before installing a python module, I'm not very familiar with python.

**Comment by wesyoung** [comment]
merged, ty!
